param()
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0;$workspace=if(-not[string]::IsNullOrWhiteSpace($env:GITHUB_WORKSPACE)){(Resolve-Path -LiteralPath $env:GITHUB_WORKSPACE).Path}else{(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path}
function Read-Text([string]$p){$f=Join-Path $workspace $p;if(-not(Test-Path -LiteralPath $f -PathType Leaf)){throw "Missing file: $p"};Get-Content -LiteralPath $f -Raw -Encoding UTF8};function Pass([string]$n){Write-Host "PASS $n";$script:checks++};function Has([string]$t,[string]$n,[string]$label){if(-not$t.Contains($n,[StringComparison]::Ordinal)){throw "Missing '$n' for $label"};Pass $label};$checks=0
$budget=Read-Text 'performance/core-web-vitals-budget.json'|ConvertFrom-Json;if($budget.schema -ne 'nova-forge-core-web-vitals-budget/v1'){throw 'CWV budget schema invalid.'};if($budget.targetBasis -ne '75th-percentile-objective' -or $budget.fieldP75MeasurementState -ne 'not-collected-pre-vf'){throw 'CWV p75 target/measurement state invalid.'};if([int]$budget.fieldTargets.lcpMs -ne 2500 -or [int]$budget.fieldTargets.inpMs -ne 200 -or [double]$budget.fieldTargets.cls -ne 0.1){throw 'CWV targets invalid.'};Pass 'core-web-vitals-p75-targets'
$js=@(Get-ChildItem -LiteralPath(Join-Path $workspace 'assets') -File|Where-Object{$_.Extension -in @('.js','.mjs')});$css=@(Get-ChildItem -LiteralPath(Join-Path $workspace 'assets') -Filter '*.css' -File);$jsBytes=($js|Measure-Object Length -Sum).Sum;$cssBytes=($css|Measure-Object Length -Sum).Sum;if($jsBytes -gt [int64]$budget.staticBudgets.maxFirstPartyJsBytes){throw "JS budget exceeded: $jsBytes"};if($cssBytes -gt [int64]$budget.staticBudgets.maxFirstPartyCssBytes){throw "CSS budget exceeded: $cssBytes"};$corePages=@('index.html','catalog.html','search.html','creator-studio.html','profiles.html','community.html','downloads.html','security.html','verify.html');foreach($page in $corePages){$f=Get-Item -LiteralPath(Join-Path $workspace $page);if($f.Length -gt [int64]$budget.staticBudgets.maxHtmlBytesPerPage){throw "HTML budget exceeded: $page $($f.Length)"}};Write-Host "PERF_BUDGET_BYTES js=$jsBytes css=$cssBytes pages=$($corePages.Count)";Pass 'static-performance-resource-budgets'
$vitals=Read-Text 'assets/vitals-budget.mjs';foreach($token in @('largest-contentful-paint','layout-shift','interactionId','sessionStorage','fieldP75Claimed: false','remoteTelemetrySent: false')){Has $vitals $token "vitals-local-$($token.Replace(':','').Replace(' ','-'))"};Has(Read-Text 'assets/shell.js') "import('./vitals-budget.mjs')" 'shell-loads-local-vitals-diagnostics'
$schema=Read-Text 'schemas/moderation-receipt.schema.json'|ConvertFrom-Json;$decisionRequired=@($schema.'$defs'.decision.required);foreach($field in @('statementOfReasons','ruleOrLegalBasis','scope','evidenceRefs','decidedAt','automatedSignalUsed','humanDecision','decisionMakerType')){if($decisionRequired -notcontains $field){throw "Moderation decision missing required field: $field"}};$appealRequired=@($schema.'$defs'.appeal.required);foreach($field in @('humanReviewRequired','automatedOnlyResolutionAllowed')){if($appealRequired -notcontains $field){throw "Appeal missing required field: $field"}};if($schema.'$defs'.appeal.properties.humanReviewRequired.const -ne $true -or $schema.'$defs'.appeal.properties.automatedOnlyResolutionAllowed.const -ne $false){throw 'Appeal human review policy invalid.'};if($schema.'$defs'.outcome.properties.humanReviewed.const -ne $true){throw 'Appeal outcome must prove human review.'};Pass 'dsa-machine-readable-receipt-contract'
$moderation=Read-Text 'assets/moderation-contract.mjs';foreach($token in @('decision-reason-basis-required','decision-evidence-refs-required','human-automation-separation-required','appeal-human-review-required','appeal-outcome-human-review-required')){Has $moderation $token "moderation-$token"}
$complaint=Read-Text 'security/human-complaint-path.json'|ConvertFrom-Json;if($complaint.humanReviewRequired -ne $true -or $complaint.automatedOnlyResolutionAllowed -ne $false){throw 'Human complaint policy invalid.'};if($null -ne $complaint.publicHumanEndpoint -or $complaint.state -ne 'BLOCKED_REAL_HUMAN_ENDPOINT_REQUIRED' -or $complaint.blockingBeforeFinal -ne $true){throw 'Human complaint endpoint must stay explicitly blocked.'};Pass 'human-complaint-path-blocker-recorded-no-fabrication'
foreach($page in $corePages){$html=Read-Text $page;if($html -notmatch '<html\b[^>]*\blang="fr"'){throw "Missing lang=fr: $page"};if($html -notmatch '<a\b[^>]*\bclass="skip-link"[^>]*\bhref="#main"'){throw "Missing skip link: $page"};if($html -notmatch '<main\b[^>]*\bid="main"'){throw "Missing main landmark: $page"};if($html -match 'tabindex="[1-9][0-9]*"'){throw "Positive tabindex forbidden: $page"};if($html -match '\sautofocus(?:\s|>|=)'){throw "Autofocus forbidden: $page"}};Pass 'accessibility-core-page-landmarks-keyboard-baseline'
$visualCss=(Read-Text 'assets/nova-premium-hd.css')+"`n"+(Read-Text 'assets/site.css');foreach($token in @(':focus-visible','min-height:44px','@media (prefers-reduced-motion:reduce)','@media (max-width:')){if(-not$visualCss.Contains($token,[StringComparison]::Ordinal)){throw "Accessibility CSS token missing: $token"}};Pass 'accessibility-focus-touch-reflow-reduced-motion-css';Has(Read-Text 'assets/shell.js') "event.key === 'Escape'" 'accessibility-keyboard-escape-navigation'
$status=Read-Text 'public-status.json'|ConvertFrom-Json;if($status.accessibility.target -ne 'WCAG 2.2 AA' -or $status.accessibility.human_review_state -ne 'required-before-final'){throw 'Accessibility public status invalid.'};if($status.moderation.human_endpoint_state -ne 'blocked-real-endpoint-required'){throw 'Human complaint blocker must be public.'};if($status.performance.field_p75_measurement_state -ne 'not-collected-pre-vf'){throw 'Field p75 must not be fabricated.'};Pass 'public-status-honest-performance-accessibility-moderation'
$sw=Read-Text 'sw.js';foreach($token in @('./performance/core-web-vitals-budget.json','./security/human-complaint-path.json','./assets/vitals-budget.mjs','./assets/moderation-contract.mjs')){Has $sw $token "pwa-caches-$($token.Replace('./','').Replace('/','-'))"};Write-Host "LOT7D_TECHNICAL_STATIC_CHECKS=$checks";node(Join-Path $workspace 'eng/site/Test-NovaSiteSuperNovaLot7D.mjs');if($LASTEXITCODE -ne 0){throw "Node Lot 7D proof failed: $LASTEXITCODE"};Write-Host "PASS_TARGETED_SITE_SUPERNOVA_LOT7D_TECHNICAL_WINDOWS_PROOF checks=$checks humanComplaint=BLOCKED_REAL_HUMAN_ENDPOINT_REQUIRED"
