param()
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0
$workspace = if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_WORKSPACE)) { (Resolve-Path -LiteralPath $env:GITHUB_WORKSPACE).Path } else { (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path }
function Read-Text([string]$RelativePath) { $path=Join-Path $workspace $RelativePath; if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Missing file: $RelativePath"}; return Get-Content -LiteralPath $path -Raw -Encoding UTF8 }
function Pass([string]$Name) { Write-Host "PASS $Name"; $script:checks++ }
function Assert-Contains([string]$Text,[string]$Needle,[string]$Name){if(-not $Text.Contains($Needle,[StringComparison]::Ordinal)){throw "Missing '$Needle' for $Name"};Pass $Name}
$checks=0
$headers=Read-Text '_headers'; Assert-Contains $headers "trusted-types 'none'" 'trusted-types-policy-locked'; Assert-Contains $headers "require-trusted-types-for 'script'" 'trusted-types-enforced'; if($headers -match "'unsafe-inline'" -or $headers -match "'unsafe-eval'"){throw 'CSP contains unsafe inline/eval fallback.'};Pass 'csp-no-unsafe-inline-eval'
$shell=Read-Text 'assets/shell.js'; Assert-Contains $shell 'securitypolicyviolation' 'privacy-safe-csp-violation-capture'; Assert-Contains $shell 'sessionStorage' 'csp-evidence-local-session-only'; Assert-Contains $shell 'slice(-19)' 'csp-evidence-bounded-ring'; if($shell -match 'blockedURI\s*:' -or $shell -match 'documentURI\s*:'){throw 'Raw CSP URLs must not be persisted.'};Pass 'csp-evidence-no-raw-uri-storage'
$domSinkPattern='(?i)(\.innerHTML\s*=|insertAdjacentHTML\s*\(|document\.write\s*\(|\beval\s*\(|new\s+Function\s*\()'; $scriptFiles=@(Get-ChildItem -LiteralPath (Join-Path $workspace 'assets') -File|Where-Object{$_.Extension -in @('.js','.mjs')}); foreach($file in $scriptFiles){$raw=Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8;if($raw -match $domSinkPattern){throw "Unsafe DOM/script sink found in $($file.Name): $($Matches[1])"}};Pass 'browser-no-unrestricted-dom-script-sinks'
$thirdParty=(Read-Text 'security/third-party-resource-policy.json'|ConvertFrom-Json);if($thirdParty.schema -ne 'nova-forge-third-party-resource-policy/v1' -or $thirdParty.mode -ne 'first-party-critical-resources-only'){throw 'Third-party policy invalid.'};if(@($thirdParty.thirdPartyDependencies).Count -ne 0){throw 'Unexpected third-party runtime dependency.'};if($thirdParty.subresourceIntegrityRequiredWhereCompatible -ne $true -or $thirdParty.immutableVersionPinRequired -ne $true){throw 'Third-party SRI/version policy incomplete.'};Pass 'third-party-first-party-only-policy'
$htmlFiles=@(Get-ChildItem -LiteralPath $workspace -Filter '*.html' -File);$externalRuntimePattern='(?is)<script[^>]+\bsrc\s*=\s*["'']https?://|<img[^>]+\bsrc\s*=\s*["'']https?://|<link[^>]+\brel\s*=\s*["''](?:stylesheet|preload|modulepreload)["''][^>]+\bhref\s*=\s*["'']https?://';foreach($file in $htmlFiles){$raw=Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8;if($raw -match $externalRuntimePattern){throw "External runtime subresource found in $($file.Name)."}};Pass 'html-no-third-party-runtime-subresources'
$asvs=(Read-Text 'security/asvs-baseline.json'|ConvertFrom-Json);if($asvs.schema -ne 'nova-forge-site-asvs-baseline/v1' -or $asvs.failClosed -ne $true){throw 'ASVS baseline contract invalid.'};$requiredSurfaces=@('authentication','creator-upload','moderation','release','storage','recovery');foreach($surface in $requiredSurfaces){if(@($asvs.surfaces) -notcontains $surface){throw "ASVS surface missing: $surface"};if(@($asvs.controls|Where-Object{@($_.surfaces) -contains $surface}).Count -lt 1){throw "No ASVS control covers $surface"}};if(@($asvs.controls).Count -lt 9){throw 'ASVS baseline control count too small.'};foreach($control in @($asvs.controls)){if($control.failClosed -ne $true -or @($control.evidence).Count -lt 1){throw "ASVS control incomplete: $($control.id)"}};Pass 'asvs-executable-baseline-all-high-risk-surfaces'
$status=(Read-Text 'public-status.json'|ConvertFrom-Json);if($status.security_contracts.browser_injection_policy -ne 'trusted-types-required-no-policy-creation'){throw 'Public status does not declare Trusted Types contract.'};if($status.security_contracts.c2pa_cryptographic_validation_provider_required -ne $true -or $status.security_contracts.c2pa_rights_ownership_inference -ne $false){throw 'C2PA public status invalid.'};if($status.security_contracts.tuf_inspired_role_separation -ne $true -or $status.security_contracts.rollback_and_expiry_fail_closed -ne $true){throw 'Update trust public status incomplete.'};if($status.integrations.update_metadata_channel -ne 'not_published' -or $status.integrations.c2pa_validation_provider -ne 'not_connected'){throw 'Unconnected trust integrations must remain fail-closed.'};Pass 'public-status-honest-7c-capability-contracts'
$c2paSchema=(Read-Text 'schemas/c2pa-evidence.schema.json'|ConvertFrom-Json);if($c2paSchema.'$id' -ne 'urn:nova-forge:schemas:c2pa-evidence:v1'){throw 'C2PA schema id invalid.'};$c2paModule=Read-Text 'assets/content-credentials.mjs';Assert-Contains $c2paModule "validationState !== 'valid'" 'c2pa-fail-closed-validation-state';Assert-Contains $c2paModule 'asset-digest-mismatch' 'c2pa-asset-binding';Assert-Contains $c2paModule 'rights-must-remain-separate' 'c2pa-rights-separation'
$updateSchema=(Read-Text 'schemas/update-trust.schema.json'|ConvertFrom-Json);if($updateSchema.'$id' -ne 'urn:nova-forge:schemas:update-trust:v1'){throw 'Update trust schema id invalid.'};$updateModule=Read-Text 'assets/update-trust.mjs';foreach($token in @('rollback-detected','timestamp-lifetime-too-long','signature-threshold-not-met','trust-key-role-reuse','timestamp-snapshot-binding-invalid','snapshot-targets-binding-invalid')){Assert-Contains $updateModule $token "update-trust-$token"}
$downloads=(Read-Text 'downloads.json'|ConvertFrom-Json);if($downloads.available -ne $false -or @($downloads.artifacts).Count -ne 0){throw 'Pre-VF downloads must remain locked with no fake artifact.'};if($downloads.range_verification_contract.required -ne $true -or $downloads.range_verification_contract.server_known_offset_required -ne $true -or $downloads.range_verification_contract.cross_release_splicing -ne 'forbidden' -or $downloads.range_verification_contract.whole_object_sha256_before_save -ne 'required'){throw 'Range download manifest contract incomplete.'};Pass 'range-download-manifest-contract'
$downloadsJs=Read-Text 'assets/downloads.js';Assert-Contains $downloadsJs 'novaVerifiedDownload' 'download-ui-uses-verified-button';if($downloadsJs -match '\.href\s*=\s*item\.download_path'){throw 'Direct unverified artifact href is forbidden.'};Pass 'download-ui-no-direct-unverified-href'
$rangeModule=Read-Text 'assets/range-verified-download.mjs';foreach($token in @('range-support-required','metadata-identity-mismatch','content-range-invalid','cross-release-or-provider-splice-blocked','whole-object-sha256-mismatch')){Assert-Contains $rangeModule $token "range-engine-$token"};Assert-Contains (Read-Text 'downloads.html') './assets/range-verified-download.mjs' 'downloads-page-loads-range-verifier'
$sw=Read-Text 'sw.js';foreach($token in @('./schemas/c2pa-evidence.schema.json','./schemas/update-trust.schema.json','./security/asvs-baseline.json','./security/third-party-resource-policy.json','./assets/content-credentials.mjs','./assets/update-trust.mjs','./assets/range-verified-download.mjs')){Assert-Contains $sw $token "pwa-caches-$($token.Replace('./','').Replace('/','-'))"}
Write-Host "LOT7C_STATIC_CHECKS=$checks";node (Join-Path $workspace 'eng/site/Test-NovaSiteSuperNovaLot7C.mjs');if($LASTEXITCODE -ne 0){throw "Node Lot 7C proof failed with exit code $LASTEXITCODE"};Write-Host "PASS_TARGETED_SITE_SUPERNOVA_LOT7C_WINDOWS_PROOF checks=$checks"
