const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict'), {webcrypto}=require('node:crypto');
const root=require('node:path').resolve(__dirname,'..');
class Node { constructor(){this.value='';this.textContent='';this.dataset={};this.listeners={};this.files=[];this.hidden=false;this.disabled=false;this.children=[];} addEventListener(k,f){(this.listeners[k]??=[]).push(f)} async fire(k){for(const f of this.listeners[k]||[])await f({preventDefault(){}})} setAttribute(k,v){this[k]=v} removeAttribute(k){delete this[k]} replaceChildren(...x){this.children=x} append(...x){this.children.push(...x)} setCustomValidity(message){this.customValidity=message} focus(){} checkValidity(){return true} reportValidity(){} reset(){} }
function env(script,opts={}){const nodes=new Map(), get=k=>{if(!nodes.has(k))nodes.set(k,new Node());return nodes.get(k)};let storage=opts.storage||{};const context={console,URL,Blob,Uint8Array,location:{hash:''},crypto:webcrypto,document:{querySelector:get,getElementById:id=>get('#'+id),createElement:()=>new Node()},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v,removeItem:k=>{if(opts.failRemove)throw Error('storage blocked');delete storage[k]}},fetch:opts.fetch||(()=>new Promise(()=>{}))};context.window=context;context.addEventListener=()=>{};vm.createContext(context);if(script==='creator-studio')vm.runInContext(fs.readFileSync(root+'/assets/json-schema-lite.js','utf8'),context);vm.runInContext(fs.readFileSync(root+'/assets/'+script+'.js','utf8'),context);return {get,context,storage};}
const flush=()=>new Promise(r=>setImmediate(r));let checks=[];
(async()=>{
 const e=env('verify');let resolve; e.get('#verify-file').files=[{name:'first',arrayBuffer:()=>new Promise(r=>resolve=r)}];e.get('#expected-sha256').value='0'.repeat(64);let pending=e.get('[data-verify-file]').fire('click');e.get('#verify-file').files=[{name:'second'}];await e.get('#verify-file').fire('change');resolve(new Uint8Array([1,2]).buffer);await pending;assert.equal(e.get('[data-verify-result]').children[0].textContent,'Vérification à relancer');assert.equal(e.get('[data-verify-file]').disabled,false);checks.push('Changed file during digest cannot publish stale match');
 e.get('#verify-file').files=[{name:'empty',arrayBuffer:async()=>new ArrayBuffer(0)}];e.get('#expected-sha256').value='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';await e.get('[data-verify-file]').fire('click');assert.equal(e.get('[data-verify-result]').dataset.state,'match');await e.get('#expected-sha256').fire('input');assert.equal(e.get('[data-verify-result]').dataset.state,'neutral');checks.push('Actual SHA256 empty-file match and invalidation after editing expected hash');
 const c=env('community',{failRemove:true,fetch:async()=>{throw Error('offline')}});c.get('#collection-id').value='valid-id';c.get('#collection-name').value='Kept';await flush();await c.get('#collection-export').fire('click');assert.match(c.get('#collection-status').textContent,/Export bloqué/);await c.get('#collection-clear').fire('click');assert.equal(c.get('#collection-name').value,'Kept');assert.match(c.get('#collection-status').textContent,/Suppression locale impossible/);c.get('#submission-heading').value='Keep submission';await c.get('#submission-clear').fire('click');assert.equal(c.get('#submission-heading').value,'Keep submission');checks.push('Offline catalogue blocks collection export; refused deletes retain both community drafts');
 const schema=JSON.parse(fs.readFileSync(root+'/schemas/universal-mod-manifest.schema.json','utf8'));const manifest={schemaVersion:1,content:{id:'test-mod',name:'Saved draft',version:'1',kind:'mod'},target:{gameId:'example',gameName:'Example',versions:[],loaders:[]},creator:{id:'creator',displayName:'Creator'},compatibility:{evidence:'unknown',dependencies:[],conflicts:[]},rights:{license:'CC0',redistribution:'unknown'},provenance:{state:'unknown'},files:[],distribution:{state:'locked',downloadable:false},releaseReceipt:null};
 let schemaResolve;const s=env('creator-studio',{storage:{'nova-forge:creator:draft:v2':JSON.stringify({draftSchema:2,manifest})},fetch:()=>new Promise(r=>schemaResolve=r),failRemove:true});assert.equal(s.get('#content-name').value,'');schemaResolve({ok:true,json:async()=>schema});await flush();assert.equal(s.get('#content-name').value,'Saved draft');assert.match(s.get('#studio-status').textContent,/restauré/);checks.push('Saved Studio draft restores only once real schema and validator are available');
 const invalid={...manifest,content:{...manifest.content,name:'Replacement'},files:[{path:'../bad',size:0,hashes:{sha256:'a'.repeat(64)}}]};s.get('#import-draft-file').files=[{text:async()=>JSON.stringify(invalid)}];await s.get('#import-draft').fire('click');assert.equal(s.get('#content-name').value,'Saved draft');assert.match(s.get('#studio-status').textContent,/Import refusé/);await s.get('#clear-draft').fire('click');assert.equal(s.get('#content-name').value,'Saved draft');assert.match(s.get('#studio-status').textContent,/impossible ou incomplète/);checks.push('Schema-invalid Studio import and storage-refused deletion preserve existing draft');
 let delayed;const d=env('creator-studio',{storage:{'nova-forge:creator:draft:v2':JSON.stringify({draftSchema:2,manifest})},fetch:()=>new Promise(r=>delayed=r)});d.get('#content-name').value='Fresh typing';await d.get('#creator-form').fire('input');delayed({ok:true,json:async()=>schema});await flush();assert.equal(d.get('#content-name').value,'Fresh typing');checks.push('Delayed schema response cannot overwrite newly typed Studio work');
 const q=env('search',{fetch:async()=>({ok:true,json:async()=>({schemaVersion:1,indexMode:'preindexed-local',externalAdapterRequired:false,entries:[]})})});await flush();assert.equal(q.get('#search-count').textContent,'0 résultats');q.get('#site-search').value='nothing';await q.get('#site-search').fire('input');assert.equal(q.get('#search-empty').hidden,false);checks.push('Valid empty search index keeps an explicit empty result state');
 console.log(JSON.stringify({result:'PASS',kind:'Node VM targeted behavioral checks; no browser claim',checks},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
